flags: {}
packages:
- '.'
extra-deps: [basic-lens-0.0.0, conversion-1.1.0.1, conversion-bytestring-1.0.0.1, conversion-text-1.0.0.2, record-0.4.0.2, record-preprocessor-0.1.0.3, record-syntax-0.1.0.2]
resolver: lts-2.17
